name: Test Service

on:
    push:
        # branches: ['master']
    pull_request:
        # branches: ['master']

jobs:
    # Job - "build"
    build-and-push-image:
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            # - name: Login to Amazon ECR
            #   id: login-ecr
            #   uses: aws-actions/amazon-ecr-login@v1

            # # Build the Docker image
            # - name: Build Image
            #   run: |
            #       make docker-build
            # # Push the Docker image to ECR
            # - name: Push Image to ECR
            #   run: |
            #       make docker-push