name: Push Docker image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Path to your Dockerfile and source code
        file: ./Dockerfile
        push: true
        tags: bivavsatyal/test:0.6
